version: '3'  

services:

######################################### Personal website container clews.pro
  nginx-clews.pro:
    image: nginx
    container_name: nginx-clews.pro
    networks:
      - nginx-proxy_reverse-proxy
      - php_php
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=${NGINX_CLEWS_PRO_URL}
      - LETSENCRYPT_HOST=${NGINX_CLEWS_PRO_URL}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ./html/:/clews.pro/html/
      - ./conf.d/:/etc/nginx/conf.d/
    restart: unless-stopped
  
######################################### Docker-managed networks
networks:
  php_php:
    external: true
  nginx-proxy_reverse-proxy:
    external: true
