######################################### Docker compose yaml file for clews.pro and sub-domains
#### Containers include:
#### - nginx-proxy              NGINX-Proxy         (image: jwilder/nginx-proxy)
#### - letsencrypt              Let's Encrypt       (image: jrcs/letsencrypt-nginx-proxy-companion)
#### - nextcloud-db             MariaDB             (image: mariadb)
#### - nextcloud-app            Nextcloud           (image: nextcloud)
#### - nextcloud-cron           Nextcloud-Cronjob   (image: rcdailey/nextcloud-cronjob)
#### - collabora-app            Collabora           (image: collabora/code)
#### - bitwarden-app            BitWarden           (image: bitwardenrs/server)
#### - nginx-clews.pro          NGINX               (image: nginx)
#### - nginx-tyler.clews.pro    NGINX               (image: nginx)

## Note some sensitive environment variables defined in external file ".env"

version: '3'  

services:

######################################### Nginx Proxy container
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    networks:
      - clews.pro_network
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d:rw
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./nginx-proxy/html:/usr/share/nginx/html:rw
      - ./nginx-proxy/certs:/etc/nginx/certs:ro
      - ./nginx-proxy/clews.pro_custom_proxy_settings.conf:/etc/nginx/conf.d/my_custom_proxy_settings.conf      #jc- added to enable nc uploads>1MB (client_max_body_size 500m)
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

######################################### Let's Encrypt container
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    networks:
      - clews.pro_network
    depends_on:
      - nginx-proxy
    volumes:
      - ./nginx-proxy/certs:/etc/nginx/certs:rw
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./nginx-proxy/html:/usr/share/nginx/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

######################################### MariaDB database (for nextcloud) container
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    networks:
      - clews.pro_network
    environment:
      - MYSQL_ROOT_PASSWORD="${MARIADB_NEXTCLOUD_MYSQL_ROOT_PASSWORD}"
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD="${MARIADB_NEXTCLOUD_MYSQL_PASSWORD}"
      - MYSQL_DATABASE=nextcloud
    volumes:
      - ./nextcloud-db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

######################################### Nextcloud web app container
  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - clews.pro_network
    depends_on:
      - letsencrypt
      - nginx-proxy
      - nextcloud-db
    environment:
      - VIRTUAL_HOST=nextcloud.clews.pro
      - LETSENCRYPT_HOST=nextcloud.clews.pro
      - LETSENCRYPT_EMAIL="${NEXTCLOUD_APP_LETSENCRYPT_EMAIL}"
    volumes:
      - ./nextcloud.clews.pro:/var/www/html
      - ./nextcloud.clews.pro/config:/var/www/html/config
      - ./nextcloud.clews.pro/custom_apps:/var/www/html/custom_apps
      - ./nextcloud.clews.pro/data:/var/www/html/data
      - ./nextcloud.clews.pro/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

######################################### Nextcloud cron container (for periodically running cron.php)
  nextcloud-cron:
    image: rcdailey/nextcloud-cronjob
    container_name: nextcloud-cron
    network_mode: none
    depends_on:
    - nextcloud-app
    environment:
    - NEXTCLOUD_CONTAINER_NAME=nextcloud-app
    - NEXTCLOUD_CRON_MINUTE_INTERVAL=5
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

######################################### Bitwarden web app container
  bitwarden-app:
    image: bitwardenrs/server:latest
    container_name: bitwarden-app
    networks:
      - clews.pro_network
    depends_on:
      - letsencrypt
      - nginx-proxy
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:3012:3012"
    environment:
      - VIRTUAL_HOST=bitwarden.clews.pro
      - LETSENCRYPT_HOST=bitwarden.clews.pro
      - LETSENCRYPT_EMAIL="${BITWARDEN_APP_LETSENCRYPT_EMAIL}"
      - SIGNUPS_ALLOWED=false
      - LOG_FILE="/data/bitwarden.log"
#      - SMTP_HOST="${BITWARDEN_APP_LETSENCRYPT_SMTP_HOST}"
#      - SMTP_FROM="${BITWARDEN_APP_LETSENCRYPT_SMTP_FROM}"
#      - SMTP_PORT=587
#      - SMTP_SSL=TLS
#      - SMTP_USERNAME="${BITWARDEN_APP_LETSENCRYPT_SMTP_USERNAME}"
#      - SMTP_PASSWORD="${BITWARDEN_APP_LETSENCRYPT_SMTP_PASSWORD}"
    volumes:
      - ./bitwarden.clews.pro/data/:/data/
    restart: unless-stopped

######################################### Collabora (for nextcloud) container
  collabora-app:
    image: collabora/code
    container_name: collabora-app
    networks:
      - clews.pro_network
    depends_on:
      - letsencrypt
      - nginx-proxy
    ports:
      - 9980:9980
    cap_add:
     - MKNOD
    environment:
      - domain=nextcloud\.clews\.pro    # jc- This nees to be the same as the nextcloud domain, with periods escaped.
      - username="${COLLABORA_APP_username}"
      - password="${COLLABORA_APP_password}"
      - VIRTUAL_PORT=9980
      - VIRTUAL_HOST=collabora.clews.pro
      - LETSENCRYPT_HOST=collabora.clews.pro
      - LETSENCRYPT_EMAIL="${COLLABORA_APP_LETSENCRYPT_EMAIL}"
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    restart: unless-stopped

######################################### Personal website container
  nginx-clews.pro:
    image: nginx
    container_name: nginx-clews.pro
    networks:
      - clews.pro_network
    depends_on:
      - letsencrypt
      - nginx-proxy
    environment:
      - NGINX_HOST=clews.pro
      - NGINX_PORT=80
      - VIRTUAL_HOST=clews.pro
      - LETSENCRYPT_HOST=clews.pro
      - LETSENCRYPT_EMAIL="${NGINX_CLEWS_PRO_LETSENCRYPT_EMAIL}"
    volumes:
      - ./clews.pro/html:/usr/share/nginx/html
    restart: unless-stopped
  
######################################### tyler website container
  nginx-tyler.clews.pro:
    image: nginx
    container_name: nginx-tyler.clews.pro
    networks:
      - clews.pro_network
    depends_on:
      - letsencrypt
      - nginx-proxy
    environment:
      - NGINX_HOST=tyler.clews.pro
      - NGINX_PORT=80
      - VIRTUAL_HOST=tyler.clews.pro
      - LETSENCRYPT_HOST=tyler.clews.pro
      - LETSENCRYPT_EMAIL="${NGINX_TYLER_CLEWS_PRO_LETSENCRYPT_EMAIL}"
    volumes:
      - ./tyler.clews.pro/html:/usr/share/nginx/html
    restart: unless-stopped

networks:
  clews.pro_network:
