######################################### Docker compose yaml file for clews.pro and sub-domains
#### Containers include:
#### - nginx-proxy              NGINX-Proxy         (image: jwilder/nginx-proxy)
#### - letsencrypt              Let's Encrypt       (image: jrcs/letsencrypt-nginx-proxy-companion)
#### - nextcloud-db             MariaDB             (image: linuxserver/mariadb)
#### - nextcloud-app            Nextcloud           (image: nextcloud)
#### - nextcloud-cron           Nextcloud-Cronjob   (image: rcdailey/nextcloud-cronjob)
#### - nextcloud-bu             NCBU                (image: ncbu/ncbu)
#### - collabora-app            Collabora           (image: collabora/code)
#### - bitwarden-app            BitWarden           (image: bitwardenrs/server)
#### - airsonic-app             Airsonic            (image: linuxserver/airsonic)
#### - nginx-clews.pro          NGINX               (image: nginx)
#### - nginx-tyler.clews.pro    NGINX               (image: nginx)
#### - nginx-jadon.clews.pro    NGINX               (image: nginx)

## Note some sensitive environment variables defined in external file ".env"

version: '3'  

services:

######################################### Nginx Proxy container
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    networks:
      - clews.pro_network
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d:rw
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./nginx-proxy/html:/usr/share/nginx/html:rw
      - ./nginx-proxy/certs:/etc/nginx/certs:ro
      - ./nginx-proxy/clews.pro_custom_proxy_settings.conf:/etc/nginx/conf.d/my_custom_proxy_settings.conf      #jc- added to enable nc uploads>1MB (client_max_body_size 500m)
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

######################################### Let's Encrypt container
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    networks:
      - clews.pro_network
    depends_on:
      - nginx-proxy
    volumes:
      - ./nginx-proxy/certs:/etc/nginx/certs:rw
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./nginx-proxy/html:/usr/share/nginx/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

######################################### MariaDB database (for nextcloud) container
  nextcloud-db:
    image: linuxserver/mariadb
    container_name: nextcloud-db
    networks:
      - clews.pro_network
    ports:
      - 3306:3306
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MARIADB_NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MARIADB_NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
    volumes:
      - nextcloud-db:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

######################################### Nextcloud web app container
  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - clews.pro_network
    depends_on:
      - letsencrypt
      - nginx-proxy
      - nextcloud-db
    environment:
      - VIRTUAL_HOST=nextcloud.clews.pro
      - LETSENCRYPT_HOST=nextcloud.clews.pro
      - LETSENCRYPT_EMAIL=${NEXTCLOUD_APP_LETSENCRYPT_EMAIL}  
    volumes:
      - nextcloud-app:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

######################################### Nextcloud cron container (for periodically running cron.php)
  nextcloud-cron:
    image: rcdailey/nextcloud-cronjob
    container_name: nextcloud-cron
    network_mode: none
    depends_on:
    - nextcloud-app
    environment:
    - NEXTCLOUD_CONTAINER_NAME=nextcloud-app
    - NEXTCLOUD_CRON_MINUTE_INTERVAL=5
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

######################################### Nextcloud backup container (for periodically copying data and database)
  nextcloud-bu:
    image: ncbu/ncbu
    container_name: nextcloud-bu
    networks:
      - clews.pro_network
    depends_on:
    - nextcloud-app
    - nextcloud-db
    environment:
    - NEXTCLOUD_CONTAINER=nextcloud-app                 # Name of the nextcloud container.
    - NEXTCLOUD_DATABASE_CONTAINER=nextcloud-db         # Name of the nextcloud database container.
    - NEXTCLOUD_BACKUP_CRON=0 0 * * *                   # Run at midnight.
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock         # Allows container to access another container.
    - /etc/localtime:/etc/localtime:ro                  # Use to sync time so that the crond runs as expected.
    - nextcloud-app:/mnt/nextcloud_app                  # Must match the docker-managed nextcloud app volume (/var/www/html).
    - nextcloud-db:/mnt/nextcloud_db                    # Must match the docker-managed nextcloud database volume (/var/lib/mysql).
    - ./nextcloud-bu:/backup                            # Convenient location for the backup.
    restart: unless-stopped

######################################### Bitwarden web app container
  bitwarden-app:
    image: bitwardenrs/server:latest
    container_name: bitwarden-app
    networks:
      - clews.pro_network
    depends_on:
      - letsencrypt
      - nginx-proxy
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:3012:3012"
    environment:
      - VIRTUAL_HOST=bitwarden.clews.pro
      - LETSENCRYPT_HOST=bitwarden.clews.pro
      - LETSENCRYPT_EMAIL=${BITWARDEN_APP_LETSENCRYPT_EMAIL}
      - SIGNUPS_ALLOWED=false
      - LOG_FILE="/data/bitwarden.log"
#      - SMTP_HOST=${BITWARDEN_APP_LETSENCRYPT_SMTP_HOST}
#      - SMTP_FROM=${BITWARDEN_APP_LETSENCRYPT_SMTP_FROM}
#      - SMTP_PORT=587
#      - SMTP_SSL=TLS
#      - SMTP_USERNAME=${BITWARDEN_APP_LETSENCRYPT_SMTP_USERNAME}
#      - SMTP_PASSWORD=${BITWARDEN_APP_LETSENCRYPT_SMTP_PASSWORD}
    volumes:
      - ./bitwarden-app/data/:/data/
    restart: unless-stopped

######################################### Collabora (for nextcloud) container
  collabora-app:
    image: collabora/code
    container_name: collabora-app
    networks:
      - clews.pro_network
    depends_on:
      - letsencrypt
      - nginx-proxy
    ports:
     - 9980:9980
    cap_add:
    - MKNOD
    environment:
     - domain=nextcloud\.clews\.pro    # jc- This needs to be the same as the nextcloud domain, with periods escaped.
     - username=${COLLABORA_APP_username}
     - password=${COLLABORA_APP_password}
     - VIRTUAL_PORT=9980
     - VIRTUAL_HOST=collabora.clews.pro
     - LETSENCRYPT_HOST=collabora.clews.pro
     - LETSENCRYPT_EMAIL=${COLLABORA_APP_LETSENCRYPT_EMAIL}
     - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    restart: unless-stopped

######################################### Personal website container
  nginx-clews.pro:
    image: nginx
    container_name: nginx-clews.pro
    networks:
      - clews.pro_network
    depends_on:
      - letsencrypt
      - nginx-proxy
    environment:
      - NGINX_HOST=clews.pro
      - NGINX_PORT=80
      - VIRTUAL_HOST=clews.pro
      - LETSENCRYPT_HOST=clews.pro
      - LETSENCRYPT_EMAIL=${NGINX_CLEWS_PRO_LETSENCRYPT_EMAIL}
    volumes:
      - ./clews.pro/html:/usr/share/nginx/html
    restart: unless-stopped
  
######################################### Airsonic container
  airsonic-app:
    image: linuxserver/airsonic
    container_name: airsonic-app
    networks:
      - clews.pro_network
    depends_on:
      - letsencrypt
      - nginx-proxy
    ports:
      - 4040:4040
    environment:
      - PUID=1000
      - PGID=1000
      - VIRTUAL_PORT=4040
      - VIRTUAL_HOST=airsonic.clews.pro
      - LETSENCRYPT_HOST=airsonic.clews.pro
      - LETSENCRYPT_EMAIL=${AIRSONIC_APP_LETSENCRYPT_EMAIL}
    volumes:
      - ./airsonic-app/config:/config
      - ./airsonic-app/music:/music
      - ./airsonic-app/playlists:/playlists
      - ./airsonic-app/podcasts:/podcasts
      - ./airsonic-app/media:/media
      - /etc/localtime:/etc/localtime:ro                  # Use to sync time so that the crond runs as expected.
    restart: unless-stopped

######################################### tyler website container
  nginx-tyler.clews.pro:
    image: nginx
    container_name: nginx-tyler.clews.pro
    networks:
      - clews.pro_network
    depends_on:
      - letsencrypt
      - nginx-proxy
    environment:
      - NGINX_HOST=tyler.clews.pro
      - NGINX_PORT=80
      - VIRTUAL_HOST=tyler.clews.pro
      - LETSENCRYPT_HOST=tyler.clews.pro
      - LETSENCRYPT_EMAIL=${NGINX_TYLER_CLEWS_PRO_LETSENCRYPT_EMAIL}
    volumes:
      - ./tyler.clews.pro/html:/usr/share/nginx/html
    restart: unless-stopped

######################################### jadon website container
  nginx-jadon.clews.pro:
    image: nginx
    container_name: nginx-jadon.clews.pro
    networks:
      - clews.pro_network
    depends_on:
      - letsencrypt
      - nginx-proxy
    environment:
      - NGINX_HOST=jadon.clews.pro
      - NGINX_PORT=80
      - VIRTUAL_HOST=jadon.clews.pro
      - LETSENCRYPT_HOST=jadon.clews.pro
      - LETSENCRYPT_EMAIL=${NGINX_JADON_CLEWS_PRO_LETSENCRYPT_EMAIL}
    volumes:
      - ./jadon.clews.pro/html:/usr/share/nginx/html
    restart: unless-stopped

######################################### Docker-managed volumes
volumes:
  nextcloud-app:
  nextcloud-db:

######################################### Docker-managed networks
networks:
  clews.pro_network:
