######################################### Docker compose yaml file for clews.pro and sub-domains
#### Containers include:
#### - nginx-proxy              nginx-proxy         (image: nginxproxy/nginx-proxy)
#### - acme-companion           acme-companion      (image: nginxproxy/acme-companion)
#### - nextcloud-db             MariaDB             (image: linuxserver/mariadb)
#### - nextcloud                Nextcloud           (image: nextcloud)
#### - nextcloud-cron           Nextcloud-Cronjob   (image: rcdailey/nextcloud-cronjob)
#### - nextcloud-bu             NCBU                (image: clewsy/ncbu)
#### - collabora                Collabora           (image: collabora/code)
#### - navidrome                Navidrome           (image: deluan/navidrome)
#### - vaultwarden              Vaultwarden         (image: vaultwarden/server)
#### - calibre                  Calibre             (image: linuxserver/calibre)
#### - calibre-web              Calibre-web         (image: linuxserver/calibre-web)
#### - php                      PHP                 (image: php:fpm)
#### - nginx-clews.pro          NGINX               (image: nginx)
#### - nginx-clews.dev          NGINX               (image: nginx)
#### - nginx-tyler.clews.pro    NGINX               (image: nginx)
#### - nginx-jadon.clews.pro    NGINX               (image: nginx)
#### - watchtower               Watchtower          (image: containrrr/watchtower)

## Note some sensitive environment variables defined in external file ".env"

version: '3'  

services:

######################################### Nginx-proxy container
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    networks:
      - clews.pro_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d:rw
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/html:/usr/share/nginx/html
      - ./nginx-proxy/dhparam:/etc/nginx/dhparam
      - ./nginx-proxy/certs:/etc/nginx/certs:ro
      - ./nginx-proxy/clews.pro_custom_proxy_settings.conf:/etc/nginx/conf.d/my_custom_proxy_settings.conf      # Enables nc uploads>1MB (client_max_body_size 500m)
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

######################################### Nginx-proxy-acme-companion container
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    networks:
      - clews.pro_network
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/html:/usr/share/nginx/html
      - ./nginx-proxy/certs:/etc/nginx/certs
      - ./nginx-proxy/acme.sh:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

######################################### MariaDB database (for nextcloud) container
  nextcloud-db:
    image: linuxserver/mariadb
    container_name: nextcloud-db
    networks:
      - clews.pro_network
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MARIADB_NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MARIADB_NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
    volumes:
      - nextcloud-db:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

######################################### Nextcloud web app container
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    networks:
      - clews.pro_network
    depends_on:
      - nginx-proxy
      - nginx-proxy-acme
      - nextcloud-db
    environment:
      - VIRTUAL_PORT=80
#      - NEXTCLOUD_OVERWRITEPROTOCOL=https
      - OVERWRITEPROTOCOL=https
      - VIRTUAL_HOST=${NEXTCLOUD_URL}
      - LETSENCRYPT_HOST=${NEXTCLOUD_URL}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - nextcloud-app:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

######################################### Nextcloud cronjob container (for periodically running cron.php)
  nextcloud-cron:
    image: rcdailey/nextcloud-cronjob
    container_name: nextcloud-cron
    network_mode: none
    depends_on:
      - nextcloud
    environment:
      - NEXTCLOUD_CONTAINER_NAME=nextcloud
      - NEXTCLOUD_CRON_MINUTE_INTERVAL=5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

######################################### Nextcloud backup container (for periodically copying data and database)
  nextcloud-bu:
    image: clewsy/ncbu
    container_name: nextcloud-bu
    network_mode: none
    depends_on:
      - nextcloud
      - nextcloud-db
    environment:
      - NEXTCLOUD_EXEC_USER=www-data                      # Name of the user that can execute the occ command in the nextcloud container (www-data by default).
      - NEXTCLOUD_CONTAINER=nextcloud                     # Name of the nextcloud container.
      - NEXTCLOUD_DATABASE_CONTAINER=nextcloud-db         # Name of the nextcloud database container.
      - NEXTCLOUD_BACKUP_CRON=0 0 * * *                   # Run at midnight.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock         # Allows container to access another container.
      - /etc/localtime:/etc/localtime:ro                  # Use to sync time so that the crond runs as expected.
      - nextcloud-app:/mnt/nextcloud_app                  # Must match the docker-managed nextcloud app volume (/var/www/html).
      - nextcloud-db:/mnt/nextcloud_db                    # Must match the docker-managed nextcloud database volume (/var/lib/mysql).
      - ./nextcloud-bu:/backup                            # Convenient location for the backup.
    restart: unless-stopped

######################################### Collabora (for nextcloud) container
  collabora:
    image: collabora/code
    container_name: collabora
    networks:
      - clews.pro_network
    depends_on:
      - nginx-proxy
      - nginx-proxy-acme
    cap_add:
      - MKNOD
    environment:
      - domain=${COLLABORA_DOMAIN}
      - username=${COLLABORA_USERNAME}
      - password=${COLLABORA_PASSWORD}
      - VIRTUAL_PORT=9980
      - VIRTUAL_HOST=${COLLABORA_URL}
      - LETSENCRYPT_HOST=${COLLABORA_URL}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    restart: unless-stopped

######################################### Navidrome container
  navidrome:
    image: deluan/navidrome
    container_name: navidrome
    networks:
      - clews.pro_network
    depends_on:
      - nginx-proxy
      - nginx-proxy-acme
    user: 1000:1000
    environment:
      - ND_SCANSCHEDULE= #Leave empty to disable (manual scan only).  Defaults to "@every 1m".
      - RecentlyAddedByModTime=true #Defaults to false.
      - ND_ENABLEGRAVATAR=true #Defaults to false.
      - VIRTUAL_PORT=4533
      - VIRTUAL_HOST=${NAVIDROME_URL}
      - LETSENCRYPT_HOST=${NAVIDROME_URL}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ./navidrome/data:/data
      - ./navidrome/music:/music
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

######################################### Vaultwarden web app container
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    networks:
      - clews.pro_network
    depends_on:
      - nginx-proxy
      - nginx-proxy-acme
    ports:
      - 8170:80 #Keep a port accessible on the local network too.
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=${VAULTWARDEN_URL}
      - LETSENCRYPT_HOST=${VAULTWARDEN_URL}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - SIGNUPS_ALLOWED=false
      - LOG_FILE="/data/vaultwarden.log"
    volumes:
      - ./vaultwarden/data/:/data/
    restart: unless-stopped

######################################### Calibre container
  calibre:
    image: linuxserver/calibre
    container_name: calibre
    networks:
      - clews.pro_network
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./calibre/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080 #Desktop gui
      - 8081:8081 #Webserver gui
      - 8082:9090 #Wireless device connection
    restart: unless-stopped

######################################### Calibre-Web container
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    networks:
      - clews.pro_network
    depends_on:
      - nginx-proxy
      - nginx-proxy-acme
      - calibre
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKER_MODS=linuxserver/calibre-web:calibre
      - VIRTUAL_PORT=8083
      - VIRTUAL_HOST=${CALIBRE_URL}
      - LETSENCRYPT_HOST=${CALIBRE_URL}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ./calibre/calibre-web/config:/config  #calibre-web specific config (separate from calibre config)
      - ./calibre/config:/books               #Map /books to the calibre container config volume (contains books/metadata)
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

######################################### php app for use by nginx containers
  php:
    image: php:fpm
    container_name: php
    networks:
      - clews.pro_network
    volumes:
      - ./clews.pro/html/:/clews.pro/html/  #Must match location of html/css/php files volume defined for clews.pro container.
      - ./clews.dev/html/:/clews.dev/html/  #Must match location of html/css/php files volume defined for clews.dev container.
    restart: unless-stopped

######################################### Personal website container clews.pro
  nginx-clews.pro:
    image: nginx
    container_name: nginx-clews.pro
    networks:
      - clews.pro_network
    depends_on:
      - nginx-proxy
      - nginx-proxy-acme
      - php
    environment:
      - NGINX_HOST=${NGINX_CLEWS_PRO_URL}
      - NGINX_PORT=80
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=${NGINX_CLEWS_PRO_URL}
      - LETSENCRYPT_HOST=${NGINX_CLEWS_PRO_URL}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ./clews.pro/html/:/clews.pro/html/
      - ./clews.pro/conf.d/:/etc/nginx/conf.d/
    restart: unless-stopped
  
######################################### clews.dev website container
  nginx-clews.dev:
    image: nginx
    container_name: nginx-clews.dev
    networks:
      - clews.pro_network
    depends_on:
      - nginx-proxy
      - nginx-proxy-acme
    environment:
      - NGINX_HOST=${NGINX_CLEWS_DEV_URL}
      - NGINX_PORT=80
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=${NGINX_CLEWS_DEV_URL}
      - LETSENCRYPT_HOST=${NGINX_CLEWS_DEV_URL}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ./clews.dev/html/:/clews.dev/html/
      - ./clews.dev/conf.d/:/etc/nginx/conf.d
    restart: unless-stopped

########################################## tyler website container
#  nginx-tyler.clews.pro:
#    image: nginx
#    container_name: nginx-tyler.clews.pro
#    networks:
#      - clews.pro_network
#    depends_on:
#      - nginx-proxy
#      - nginx-proxy-acme
#    environment:
#      - NGINX_HOST=${NGINX_TYLER_CLEWS_PRO_URL}
#      - NGINX_PORT=80
#      - VIRTUAL_PORT=80
#      - VIRTUAL_HOST=${NGINX_TYLER_CLEWS_PRO_URL}
#      - LETSENCRYPT_HOST=${NGINX_TYLER_CLEWS_PRO_URL}
#      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
#    volumes:
#      - ./tyler.clews.pro/html:/usr/share/nginx/html
#    restart: unless-stopped

########################################## jadon website container
#  nginx-jadon.clews.pro:
#    image: nginx
#    container_name: nginx-jadon.clews.pro
#    networks:
#      - clews.pro_network
#    depends_on:
#      - nginx-proxy
#      - nginx-proxy-acme
#    environment:
#      - NGINX_HOST=${NGINX_JADON_CLEWS_PRO_URL}
#      - NGINX_PORT=80
#      - VIRTUAL_PORT=80
#      - VIRTUAL_HOST=${NGINX_JADON_CLEWS_PRO_URL}
#      - LETSENCRYPT_HOST=${NGINX_JADON_CLEWS_PRO_URL}
#      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
#    volumes:
#      - ./jadon.clews.pro/html:/usr/share/nginx/html
#    restart: unless-stopped

######################################### Watchtower container
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true #Remove old images.
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
      - WATCHTOWER_SCHEDULE=0 30 4 * * * #Daily at 0430hrs.
#      - WATCHTOWER_DEBUG=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #Mount docker.sock to give watchtower ability to control docker.
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped

######################################### Docker-managed volumes
volumes:
  nextcloud-app:
  nextcloud-db:

######################################### Docker-managed networks
networks:
  clews.pro_network:
